version: '3.7'
services:
  mysql:
    build:
      context: ./note-taking-dockers/mysql
      dockerfile: ./Dockerfile
    container_name: local-mysql
    network_mode: host
    environment:
      - MYSQL_DATABASE=keycloak_db
      - MYSQL_ROOT_PASSWORD=12345678
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --character-set-filesystem=utf8 --lower_case_table_names=1
    volumes:
      - volume-mysql:/var/lib/mysql
  keycloak:
    build:
      context: ./note-taking-dockers/keycloak
      dockerfile: ./Dockerfile
    container_name: local-keycloak
    network_mode: host
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://localhost:3306/keycloak_db?characterEncoding=UTF-8
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: 12345678
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    command: start-dev
    depends_on:
      - mysql
    volumes:
      - volume-keycloak:/var/lib/local-keycloak
  java-app:
    build:
      context: ./
      dockerfile: ./java-app-docker/Dockerfile
    container_name: java-app
    network_mode: host
    depends_on:
      - mysql
      - keycloak
  react-app:
    build:
      context: ./
      dockerfile: ./react-app-docker/Dockerfile
    container_name: react-app
    network_mode: host
    depends_on:
      - mysql
      - keycloak

volumes:
  volume-mysql:
  volume-keycloak: